### ISSUE TITLE
Prepare package for shipping

### ISSUE THREAD

**Issue by peanutfun** [ElcoK/osm-flex#5]
This is a list of task to make the package conform to best practices for `setuptools`, see https://setuptools.pypa.io/en/latest/references/keywords.html:

* Require setuptools >=64.0.0 to ensure that no `setup.py` is needed
* Add `pytest` to test requirements, it's the best tool to run tests (also `unittest` tests)
* Move tests out of the source directory into `tests/`. See https://docs.pytest.org/en/latest/explanation/goodpractices.html#tests-outside-application-code
* Register the `.ini` file as `package_data` (it will otherwise not be shipped)
* Remove stray `.DS_Store` file, update `.gitignore` accordingly
* Verify that `package_dir` is not needed (because of src-layout), see https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#automatic-discovery
* Remove `requirements.txt`, it is is obsolete due to `pyproject.toml`
* Add extra requirements for running the tutorials (Jupyter Notebooks)
* Drop `pandas`, `shapely`, `numpy` from requirements, they are dependencies of `geopandas` already
* Remove `readme` key, it is not supported

**Comment by Evelyn-M** [comment]
These were addressed in pull request #7
